# $Id$

SYSROOT = ../../../..

include ${SYSROOT}/lib/mk/defs.mk

CLASSES += cancel.class index.class output.class remove.class
CLASSES += status.class submit.class
TARGET = ${CLASSES}

include ${MAINMK}
