# $Id$

SYSROOT = ../..

include ${SYSROOT}/lib/mk/defs.mk

CLASSES += OOFBadElementFormException.class OOFException.class OOF.class
SUBDIRS += element filter t
TARGET = ${CLASSES}

include ${MAINMK}
