# $Id$

CLASSES += Break.class Code.class DivisionEnd.class Division.class
CLASSES += DivisionStart.class Element.class ELEMENT.class Email.class
CLASSES += Emphasis.class Endable.class END.class Fieldset.class
CLASSES += FormEnd.class Form.class FormStart.class Header.class
CLASSES += HorizontalRuler.class Image.class Input.class Link.class
CLASSES += ListEnd.class ListItem.class List.class ListStart.class
CLASSES += Paragraph.class Preformatted.class Span.class Startable.class
CLASSES += START.class Strong.class TableEnd.class Table.class
CLASSES += TableRow.class TableStart.class

SYSROOT = ../../..

include ${SYSROOT}/lib/mk/defs.mk

include ${MAINMK}
