# $Id$

SYSROOT = ../../..

include ${SYSROOT}/lib/mk/defs.mk

# Interfaces
CLASSES += Elementable.class Endable.class Startable.class

# Generic classes
CLASSES += _Element.class _End.class _Start.class

# Start/end
CLASSES += DivisionEnd.class DivisionStart.class
CLASSES += FormEnd.class FormStart.class
CLASSES += ListEnd.class ListStart.class
CLASSES += TableEnd.class TableStart.class

# Core classes
CLASSES += Break.class Code.class Division.class Email.class
CLASSES += Emphasis.class Endable.class Fieldset.class Form.class
CLASSES += Header.class HorizontalRuler.class Image.class Input.class
CLASSES += Link.class ListItem.class List.class Option.class
CLASSES += Paragraph.class Preformatted.class Select.class Span.class
CLASSES += Strong.class Table.class Textarea.class TableCell.class
CLASSES += TableRow.class
TARGET = ${CLASSES}

include ${MAINMK}
