# $Id$

CLASSES += Break Code DivisionEnd Division DivisionStart Element
CLASSES += ELEMENT Email Emphasis Endable END Fieldset FormEnd
CLASSES += Form FormStart Header HorizontalRuler Image Input
CLASSES += Link ListEnd ListItem List ListStart Paragraph
CLASSES += Preformatted Span Startable START Strong TableEnd
CLASSES += Table TableRow TableStart

SYSROOT = ../../..

include ${SYSROOT}/lib/mk/defs.mk

include ${MAINMK}
