# $Id$

SYSROOT = ../../..

include ${SYSROOT}/lib/mk/defs.mk

CLASSES += JobList.class GridJob.class GramInt.class GridInt.class
CLASSES += RSLElement.class GassInt.class UserMap.class
SUBDIRS += auth t
TARGET = ${CLASSES}
CLEAN += DN.class

include ${MAINMK}
