# $Id$

SYSROOT = ../../..

include ${SYSROOT}/lib/mk/defs.mk

CLASSES += GridJobList.class GridJob.class GramInt.class GridInt.class
CLASSES += RSLElement.class
SUBDIRS += auth t
TARGET = ${CLASSES}

include ${MAINMK}
