# $Id$

SYSROOT = ../../..

include ${SYSROOT}/lib/mk/defs.mk

CLASSES += JobList.class GridJob.class GramInt.class GridInt.class
CLASSES += RSLElement.class GassInt.class
SUBDIRS += auth t
TARGET = ${CLASSES}

include ${MAINMK}
