# $Id$

SYSROOT = ../../..

include ${SYSROOT}/lib/mk/defs.mk

CLASSES += login.class logout.class index.class nodes.class
CLASSES += notfound.class
SUBDIRS += jobs rls
TARGET = ${CLASSES}

include ${MAINMK}
