# $Id$

SYSROOT = ..

include ${SYSROOT}/lib/mk/defs.mk

CLASSES += Page.class GridFE.class
PRIVCLASSES += DelegationHandler.class NavigationMenu.class
SUBDIRS += gridint
TARGET = ${CLASSES}

include ${MAINMK}
