# $Id$

SYSROOT = ../..

include ${SYSROOT}/lib/mk/defs.mk

CLASSES += Page.class GridFE.class
CLEAN += DelegationHandler.class Menu.class
SUBDIRS += gridint www
TARGET = ${CLASSES}

include ${MAINMK}
